Create 2018-09-05
nodejs/board pull request #80
Opened 2018-10-23 15:22 UTC by namdeirf

Here are the draft minutes from the Sept. 5, 2018 public session of the Nodejs board.

2018-10-23 15:39 UTC, MylesBorins commented on minutes/2018-09-05
> +Gaurav Seth (Microsoft), Todd Moore (IBM), Sarah Novotny (Google), William Kapke (Individual Director), Scott Hammond (Joyent), Tracy Hinds (Individual Director), Brian McCallister (Silver Director,
I believe I was in attendance

2018-10-23 15:39 UTC, MylesBorins commented on minutes/2018-09-05
> +Gaurav Seth (Microsoft), Todd Moore (IBM), Sarah Novotny (Google), William Kapke (Individual Director), Scott Hammond (Joyent), Tracy Hinds (Individual Director), Brian McCallister (Silver Director,
Tracy should also be listed as CommComm Director (not individual)

2018-10-23 17:17 UTC, williamkapke commented
@namdeirf Thanks a million for posting this! I renamed the file with the ".md" extension so it will display on GitHub.

2018-10-23 17:26 UTC, williamkapke requested changes

2018-10-23 17:26 UTC, williamkapke commented on minutes/2018-09-05.md
> +
Since I renamed the file, GitHub is hiding @MylesBorins's comments. Reposting to make sure they don't get missed:
> I believe I was in attendance
> Tracy should also be listed as CommComm Director (not individual)

2018-10-23 17:26 UTC, williamkapke commented on minutes/2018-09-05.md
> +# Andrew Updegrove (Gesmer Updegrove LLP)
Markdown formatting error. Probably just a goof with the conversion. Please remove the '#' from the beginning of this line.

2018-10-23 17:26 UTC, williamkapke commented on minutes/2018-09-05.md
> +Director Hammond called on the Directors to approve the minutes of the public session of the June 2018 meeting of the Board of Directors. Upon motion duly made by Director Moore, seconded by Director
I believe this is supposed to say `except for Director Kapke` instead of `save for Director Kapke`

2018-10-23 17:26 UTC, williamkapke commented on minutes/2018-09-05.md
> +# At 4:35 pm Pacific Time, Director Moore adjourned the public session.
Formatting error: Please remove the `#` from the beginning of this line.

2019-07-16 21:08 UTC, Trott commented
Closing stale issues and PRs as the repository is being archived.

2019-07-16 21:08 UTC, closed without merging